services:
  postgres-db:
    image: postgres:15.8
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tracker_time_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - spring-postgres-network

  app-service:
    build: .
    container_name: time-tracker-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/tracker_time_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      SPRING_JPA_SHOW_SQL: "true"
      JWT_TOKEN_EXPIRATION_TIME: 10000
      JWT_SECRET: c87f94e5-64ec-455a-a73b-e6c6c759c2e6
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    networks:
      - spring-postgres-network

volumes:
  postgres-data:

networks:
  spring-postgres-network: