CREATE TABLE user_security
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login    VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role     VARCHAR(255) NOT NULL
);


CREATE TABLE project
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_name VARCHAR(255) NOT NULL,
    user_id      BIGINT,
    CONSTRAINT fk_user FOREIGN KEY (user_id)
        REFERENCES user_security (id)
        ON DELETE SET NULL
);


CREATE TABLE record_time
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    total_time NUMERIC(21, 0) NOT NULL,
    project_id BIGINT,
    user_id    BIGINT,
    CONSTRAINT fk_project FOREIGN KEY (project_id)
        REFERENCES project (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_user FOREIGN KEY (user_id)
        REFERENCES user_security (id)
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX user_security_login_uindex
    ON user_security (login);
